ALTER SEQUENCE endereco_ENDERECO_ID_seq RESTART WITH 1;
insert into endereco(rua, bairro, cidade, estado, cep) values ('Avenida Tiradentes','Morumbi','São Paulo','São Paulo','08260-310');
insert into endereco(rua, bairro, cidade, estado, cep) values ('Avenida Paulista','Bom Clima','São Paulo','São Paulo','08420-220');
insert into endereco(rua, bairro, cidade, estado, cep) values ('Avenida Brasil','Tatuapé','São Paulo','São Paulo','08485-501');
insert into endereco(rua, bairro, cidade, estado, cep) values ('Avenida Tupinamba','Penha','São Paulo','São Paulo','04736-050');

ALTER SEQUENCE GERENTE_GERENTE_ID_seq RESTART WITH 1;

INSERT INTO GERENTE (EMAIL, CPF_GERENTE, NOME_GER, SOBRENOME_GER) values ('leandroben-78@mac.com','99698151214','Leandro','Benjamin Raimundo Castro');

ALTER SEQUENCE FRANQUIA_FRANQUIA_ID_seq RESTART WITH 1;

INSERT INTO FRANQUIA (GERENTE_ID, ENDERECO_ID, UNIDADE_FRANQUIA) values (1,1,'Morumbi');

ALTER SEQUENCE CARRO_CARRO_ID_seq RESTART WITH 1;

INSERT INTO CARRO (FRANQUIA_ID, PLACA, MODELO, ANO, MARCA_CARRO) values (1,'MYE-5324','HOVER', '2011', 'GREAT WALL');
INSERT INTO CARRO (FRANQUIA_ID, PLACA, MODELO, ANO, MARCA_CARRO) values (1,'KET-5988','ULC PICAPE', '2017', 'EFFA');
INSERT INTO CARRO (FRANQUIA_ID, PLACA, MODELO, ANO, MARCA_CARRO) values (1,'BEL-8931','Camper', '2006', 'Envemo');

ALTER SEQUENCE CLIENTE_CLIENTE_ID_seq RESTART WITH 1;

INSERT INTO CLIENTE (CPF_CLIENTE, CELULAR, ENDERECO_ID, NOME_CLI, SOBRENOME_CLI) values ('76740949522','79998368381',2,'Aline', 'Mariane Porto');
INSERT INTO CLIENTE (CPF_CLIENTE, CELULAR, ENDERECO_ID, NOME_CLI, SOBRENOME_CLI) values ('69396135283','96995710062',3,'Benjamin', 'Ian');
INSERT INTO CLIENTE (CPF_CLIENTE, CELULAR, ENDERECO_ID, NOME_CLI, SOBRENOME_CLI) values ('34515611909','94988242210',4,'Guilherme', 'Antonio');


ALTER SEQUENCE FUNCIONARIO_FUNCIONARIO_ID_seq RESTART WITH 1;

INSERT INTO FUNCIONARIO (NOME_FUNC, SOBRENOME_FUNC, CARGO, FRANQUIA_ID, DATA_ADMISSAO, CPF_FUNC) values ('Francisco', 'Lorenzo', 'repositor', 1, '23/08/1961', '90086033301'); 
INSERT INTO FUNCIONARIO (NOME_FUNC, SOBRENOME_FUNC, CARGO, FRANQUIA_ID, DATA_ADMISSAO, CPF_FUNC) values ('Nicolas', 'Henry', 'repositor', 1, '26/02/1963', '52588732771'); 
INSERT INTO FUNCIONARIO (NOME_FUNC, SOBRENOME_FUNC, CARGO, FRANQUIA_ID, DATA_ADMISSAO, CPF_FUNC) values ('Marlene', 'Luana', 'repositor', 1, '22/08/1961', '28268557516'); 
INSERT INTO FUNCIONARIO (NOME_FUNC, SOBRENOME_FUNC, CARGO, FRANQUIA_ID, DATA_ADMISSAO, CPF_FUNC) values ('Danilo', 'Elias', 'repositor', 1, '20/04/1965', '02589683898'); 
INSERT INTO FUNCIONARIO (NOME_FUNC, SOBRENOME_FUNC, CARGO, FRANQUIA_ID, DATA_ADMISSAO, CPF_FUNC) values ('Clara', 'Aurora', 'repositor', 1, '05/02/1960', '65431718398'); 
INSERT INTO FUNCIONARIO (NOME_FUNC, SOBRENOME_FUNC, CARGO, FRANQUIA_ID, DATA_ADMISSAO, CPF_FUNC) values ('Eliane', 'Amanda', 'caixa', 1, '08/09/1969', '46090565776'); 
INSERT INTO FUNCIONARIO (NOME_FUNC, SOBRENOME_FUNC, CARGO, FRANQUIA_ID, DATA_ADMISSAO, CPF_FUNC) values ('Carolina', 'Carolina', 'caixa', 1, '14/06/1957', '14799449125'); 
INSERT INTO FUNCIONARIO (NOME_FUNC, SOBRENOME_FUNC, CARGO, FRANQUIA_ID, DATA_ADMISSAO, CPF_FUNC) values ('Luiz', 'Arthur', 'caixa', 1, '01/04/1986', '82795860406'); 
INSERT INTO FUNCIONARIO (NOME_FUNC, SOBRENOME_FUNC, CARGO, FRANQUIA_ID, DATA_ADMISSAO, CPF_FUNC) values ('Rafael', 'Caue', 'caixa', 1, '02/08/1974', '51186969172'); 

INSERT INTO CLT (FUNCIONARIO_ID, SALARIO) values (1, '1650');
INSERT INTO CLT (FUNCIONARIO_ID, SALARIO) values (2, '1650');
INSERT INTO CLT (FUNCIONARIO_ID, SALARIO) values (3, '1650');
INSERT INTO CLT (FUNCIONARIO_ID, SALARIO) values (4, '1650');
INSERT INTO CLT (FUNCIONARIO_ID, SALARIO) values (5, '1650');
INSERT INTO CLT (FUNCIONARIO_ID, SALARIO) values (6, '1650');
INSERT INTO CLT (FUNCIONARIO_ID, SALARIO) values (7, '1650');
INSERT INTO CLT (FUNCIONARIO_ID, SALARIO) values (8, '1650');
INSERT INTO CLT (FUNCIONARIO_ID, SALARIO) values (9, '1650');

ALTER SEQUENCE VENDA_VENDA_ID_seq RESTART WITH 1;

INSERT INTO VENDA (FUNCIONARIO_ID, FRANQUIA_ID, CLIENTE_ID, CAIXA, VALOR, DATA_VENDA, PARCELAS) values (1, 1, 1, '3', '443', '22/05/2020', 1);
INSERT INTO VENDA (FUNCIONARIO_ID, FRANQUIA_ID, CLIENTE_ID, CAIXA, VALOR, DATA_VENDA, PARCELAS) values (2, 1, 2, '5', '229', '22/05/2020', 2);
INSERT INTO VENDA (FUNCIONARIO_ID, FRANQUIA_ID, CLIENTE_ID, CAIXA, VALOR, DATA_VENDA, PARCELAS) values (3, 1, 3, '2', '250', '22/05/2020', 2);
INSERT INTO VENDA (FUNCIONARIO_ID, FRANQUIA_ID, CLIENTE_ID, CAIXA, VALOR, DATA_VENDA, PARCELAS) values (4, 1, 2, '4', '485', '22/05/2020', 3);
INSERT INTO VENDA (FUNCIONARIO_ID, FRANQUIA_ID, CLIENTE_ID, CAIXA, VALOR, DATA_VENDA, PARCELAS) values (5, 1, 3, '4', '402', '22/05/2020', 2);
INSERT INTO VENDA (FUNCIONARIO_ID, FRANQUIA_ID, CLIENTE_ID, CAIXA, VALOR, DATA_VENDA, PARCELAS) values (6, 1, 3, '4', '319', '22/05/2020', 5);
INSERT INTO VENDA (FUNCIONARIO_ID, FRANQUIA_ID, CLIENTE_ID, CAIXA, VALOR, DATA_VENDA, PARCELAS) values (7, 1, 1, '3', '375', '22/05/2020', 4);


ALTER SEQUENCE FORNECEDOR_FORNECEDOR_ID_seq RESTART WITH 1;

INSERT INTO FORNECEDOR (NOME_FORN, CNPJ_FORNECEDOR, EMAIL_FORNECEDOR) values ('Limpeza SA', '50328594000132', 'limpeza@gmail.com');
INSERT INTO FORNECEDOR (NOME_FORN, CNPJ_FORNECEDOR, EMAIL_FORNECEDOR) values ('Bebidas SA', '75847095000182', 'bebidas@gmail.com');
INSERT INTO FORNECEDOR (NOME_FORN, CNPJ_FORNECEDOR, EMAIL_FORNECEDOR) values ('Alimentos SA', '74125597000137', 'alimentos@gmail.com');
INSERT INTO FORNECEDOR (NOME_FORN, CNPJ_FORNECEDOR, EMAIL_FORNECEDOR) values ('Panelas SA', '42212013000174', 'panelas@gmail.com');
INSERT INTO FORNECEDOR (NOME_FORN, CNPJ_FORNECEDOR, EMAIL_FORNECEDOR) values ('Verduras SA', '01153338000146', 'verduras@gmail.com');

ALTER SEQUENCE FORNECIMENTO_FORNECIMENTO_ID_seq RESTART WITH 1;

INSERT INTO FORNECIMENTO (FRANQUIA_ID, FORNECEDOR_ID, DATA_FORN) values (1, 1, '12/05/2020');
INSERT INTO FORNECIMENTO (FRANQUIA_ID, FORNECEDOR_ID, DATA_FORN) values (1, 2, '12/05/2020');
INSERT INTO FORNECIMENTO (FRANQUIA_ID, FORNECEDOR_ID, DATA_FORN) values (1, 3, '12/05/2020');
INSERT INTO FORNECIMENTO (FRANQUIA_ID, FORNECEDOR_ID, DATA_FORN) values (1, 5, '12/05/2020');
INSERT INTO FORNECIMENTO (FRANQUIA_ID, FORNECEDOR_ID, DATA_FORN) values (1, 4, '12/05/2020');
INSERT INTO FORNECIMENTO (FRANQUIA_ID, FORNECEDOR_ID, DATA_FORN) values (1, 4, '12/05/2020');

ALTER SEQUENCE SECAO_SECAO_ID_seq RESTART WITH 1;

INSERT INTO secao (NOME_SEC) values ('Comestiveis');
INSERT INTO secao (NOME_SEC) values ('Limpeza');
INSERT INTO secao (NOME_SEC) values ('Utensilios');

ALTER SEQUENCE PRODUTO_PRODUTO_ID_seq RESTART WITH 1;

INSERT INTO PRODUTO (SECAO_ID, FRANQUIA_ID, FORNECIMENTO_ID, VENDA_ID, MARCA_PRODUTO, PRECO_UNITARIO, NOME_PRODUTO) values (1, 1, 6, 1, 'Tramontina', '23', 'Panela de Pressao');
INSERT INTO PRODUTO (SECAO_ID, FRANQUIA_ID, FORNECIMENTO_ID, VENDA_ID, MARCA_PRODUTO, PRECO_UNITARIO, NOME_PRODUTO) values (1, 1, 6, 2, 'Tramontina', '75', 'Chaleira');
INSERT INTO PRODUTO (SECAO_ID, FRANQUIA_ID, FORNECIMENTO_ID, VENDA_ID, MARCA_PRODUTO, PRECO_UNITARIO, NOME_PRODUTO) values (1, 1, 5, 3, 'Tramontina', '5', 'Garfo e faca');
INSERT INTO PRODUTO (SECAO_ID, FRANQUIA_ID, FORNECIMENTO_ID, VENDA_ID, MARCA_PRODUTO, PRECO_UNITARIO, NOME_PRODUTO) values (2, 1, 5, 4, 'Tramontina', '4', 'Colher');
INSERT INTO PRODUTO (SECAO_ID, FRANQUIA_ID, FORNECIMENTO_ID, VENDA_ID, MARCA_PRODUTO, PRECO_UNITARIO, NOME_PRODUTO) values (2, 1, 1, 5, 'Candida', '36', 'detegente neutro');
INSERT INTO PRODUTO (SECAO_ID, FRANQUIA_ID, FORNECIMENTO_ID, VENDA_ID, MARCA_PRODUTO, PRECO_UNITARIO, NOME_PRODUTO) values (2, 1, 1, 6, 'Vanish', '44', 'Alvejante');
INSERT INTO PRODUTO (SECAO_ID, FRANQUIA_ID, FORNECIMENTO_ID, VENDA_ID, MARCA_PRODUTO, PRECO_UNITARIO, NOME_PRODUTO) values (2, 1, 2, 7, 'Skol', '67', 'Cerveja lata');
INSERT INTO PRODUTO (SECAO_ID, FRANQUIA_ID, FORNECIMENTO_ID, VENDA_ID, MARCA_PRODUTO, PRECO_UNITARIO, NOME_PRODUTO) values (3, 1, 2, 2, 'Brahma', '85', 'Duplo Malte');
INSERT INTO PRODUTO (SECAO_ID, FRANQUIA_ID, FORNECIMENTO_ID, VENDA_ID, MARCA_PRODUTO, PRECO_UNITARIO, NOME_PRODUTO) values (3, 1, 3, 3, 'Adria', '26', 'Macarrao');
INSERT INTO PRODUTO (SECAO_ID, FRANQUIA_ID, FORNECIMENTO_ID, MARCA_PRODUTO, PRECO_UNITARIO, NOME_PRODUTO) values (3, 1, 4, 'marca 10', '89', 'Produto 10');

ALTER SEQUENCE PROMOCAO_PROMOCAO_ID_seq RESTART WITH 1;